runs:
  using: composite
  steps:
    - run: |
        mkdir -p ~/.ssh
        echo "${{ env.VPS_GAMESERVER_OPENSSH_PRIVATE_KEY }}" > ~/.ssh/${{ env.VPS_GAMESERVER_OPENSSH_ID }}
        chmod 600 ~/.ssh/${{ env.VPS_GAMESERVER_OPENSSH_ID }}
        ssh-keyscan ${{ env.VPS_HOSTNAME }} >> ~/.ssh/known_hosts
      shell: bash
