// dod_zalec.res - created with RESGen v2.0.3.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (74):
decals.wad
dod_avalanche.wad
dod_zalec.wad
gfx/env/snowcliffbk.tga
gfx/env/snowcliffdn.tga
gfx/env/snowcliffft.tga
gfx/env/snowclifflf.tga
gfx/env/snowcliffrt.tga
gfx/env/snowcliffup.tga
halflife.wad
hlbasics.wad
models/mapmodels/bulb.mdl
models/mapmodels/by_barrel_brown.mdl
models/mapmodels/by_barrels_pallet.mdl
models/mapmodels/by_furniture_group-wreck.mdl
models/mapmodels/by_statue_snow.mdl
models/mapmodels/car021.mdl
models/mapmodels/dinner_table1.mdl
models/mapmodels/dinner_table2.mdl
models/mapmodels/dod_jagd_car.mdl
models/mapmodels/door1.mdl
models/mapmodels/flags.mdl
models/mapmodels/forts.mdl
models/mapmodels/grandfather_clock1.mdl
models/mapmodels/hk_radio.mdl
models/mapmodels/messerschmitt_tail.mdl
models/mapmodels/null.mdl
models/mapmodels/posts.mdl
models/mapmodels/sandbags.mdl
models/mapmodels/snow_panzer.mdl
models/mapmodels/stang.mdl
models/mapmodels/street_lamp1.mdl
models/mapmodels/wood_barrel1.mdl
models/mapmodels/zalec_1bulb2wire.mdl
models/mapmodels/zalec_2bulb1wire.mdl
models/mapmodels/zalec_2bulb2wire.mdl
models/mapmodels/zalec_snowhill.mdl
models/mapmodels/zalec_tree1.mdl
models/mapmodels/zalec_window.mdl
models/metalplategibs.mdl
overviews/dod_zalec.bmp
overviews/dod_zalec.txt
sound/ambience/burning1.wav
sound/ambience/burning2.wav
sound/ambience/clock-tic.wav
sound/ambience/dodambience5.wav
sound/ambience/flyby.wav
sound/ambience/gerareasecure.wav
sound/ambience/germanwin.wav
sound/ambience/radio_morse.wav
sound/ambience/usobjectivesecure.wav
sound/ambience/uswin.wav
sound/player/gerenemyahead.wav
sound/player/usenemyahead.wav
sound/player/usfallback.wav
sound/weapons/Garand_shoot.wav
sound/weapons/Kar_shoot.wav
sound/weapons/mortar.wav
sprites/explosion1.spr
sprites/gas_puff_01.spr
sprites/mapsprites/fexplo.spr
sprites/mapsprites/beep.spr
sprites/mapsprites/c2_5to1count.spr
sprites/mapsprites/caparea.spr
sprites/mapsprites/explosion_smoke1.spr
sprites/mapsprites/fexplo.spr
sprites/mapsprites/fire.spr
sprites/mapsprites/flames.spr
sprites/mapsprites/soldier_tnt.spr
sprites/mapsprites/xsmoke3.spr
sprites/obj_tnt.spr
sprites/smoke_ia.spr
sprites/xsmoke3.spr
sprites/xssmke1.spr
