// dod_liberte_b2.res - created with RESGen v2.0.3.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (95):
dod_anzio.wad
dod_avalanche.wad
dod_caen.wad
dod_charlie.wad
dod_chemille.wad
dod_donner.wad
dod_escape.wad
dod_falaise.wad
dod_flash.wad
dod_flugplatz.wad
dod_forest.wad
dod_glider.wad
dod_jagd.wad
dod_kraftstoff.wad
dod_merderet.wad
dod_northbound.wad
dod_saints.wad
dod_sturm.wad
dod_vicenza.wad
gfx/env/grnplsntbk.tga
gfx/env/grnplsntdn.tga
gfx/env/grnplsntft.tga
gfx/env/grnplsntlf.tga
gfx/env/grnplsntrt.tga
gfx/env/grnplsntup.tga
models/mapmodels/barbed_wire.mdl
models/mapmodels/barber_chair.mdl
models/mapmodels/bed_empty-wood.mdl
models/mapmodels/bicycle.mdl
models/mapmodels/bicycle_dead.mdl
models/mapmodels/big_water_tower.mdl
models/mapmodels/bord.mdl
models/mapmodels/by_rubble_set.mdl
models/mapmodels/charlie_plans.mdl
models/mapmodels/dk_tree4.mdl
models/mapmodels/dn_hotel_mailbox.mdl
models/mapmodels/dn_piano.mdl
models/mapmodels/dod_jagd_car.mdl
models/mapmodels/fan_ceiling-hang.mdl
models/mapmodels/flo_becken.mdl
models/mapmodels/flo_bed.mdl
models/mapmodels/flo_bush.mdl
models/mapmodels/flo_coattree.mdl
models/mapmodels/flo_grass.mdl
models/mapmodels/flo_pak37.mdl
models/mapmodels/flo_piano.mdl
models/mapmodels/flo_radio.mdl
models/mapmodels/flo_toilet.mdl
models/mapmodels/furniture_group-hotel01.mdl
models/mapmodels/grandfather_clock1.mdl
models/mapmodels/jeep.mdl
models/mapmodels/ME262.mdl
models/mapmodels/pi_tree3.mdl
models/mapmodels/radiator.mdl
models/mapmodels/repunzel_bott.mdl
models/mapmodels/sandbags.mdl
models/mapmodels/sherman.mdl
models/mapmodels/sign_shop.mdl
models/mapmodels/tol_carwreck1.mdl
models/mapmodels/truck.mdl
models/TACT2021/88flakup.mdl
models/tact2021/ae_smallbush.mdl
models/tact2021/bulb.mdl
models/tact2021/flo_chairnew.mdl
models/TACT2021/flo_sandbag1337.mdl
models/tact2021/lamp.mdl
models/tact2021/pooptub.mdl
models/TACT2021/repunzbottles.mdl
models/TACT2021/tactrub.mdl
models/TACT2021/trash1.mdl
models/TACT2021/trash3.mdl
models/TACT2021/trash_02.mdl
models/w_aflag.mdl
models/w_gflag.mdl
models/w_wflag.mdl
overviews/dod_liberte_b2.bmp
overviews/dod_liberte_b2.txt
sound/ambience/burning1.wav
sound/ambience/burning16a.wav
sound/ambience/burning3.wav
sound/ambience/dod_jagd_radio.wav
sound/ambience/dodambience3.wav
sound/ambience/gerareasecure.wav
sound/ambience/germanwin.wav
sound/ambience/truck-1ka.wav
sound/ambience/usareasecure.wav
sound/ambience/uswin.wav
sound/ambience/windy.wav
sound/weapons/30cal_shoot.wav
sprites/flames.spr
sprites/laserbeam.spr
sprites/mapsprites/caparea.spr
sprites/muzzleflash2.spr
sprites/obj_tnt.spr
sprites/smoke_ia.spr
