// \dod_glider.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (95):
dod_donner.wad
dod_escape.wad
dod_falaise.wad
dod_flugplatz.wad
dod_glider.wad
dod_jagd.wad
gfx/env/kraftstoffbk.tga
gfx/env/kraftstoffdn.tga
gfx/env/kraftstoffft.tga
gfx/env/kraftstofflf.tga
gfx/env/kraftstoffrt.tga
gfx/env/kraftstoffup.tga
halflife.wad
hlbasics.wad
models/mapmodels/88flak.mdl
models/mapmodels/arc_bush.mdl
models/mapmodels/barbed_wire.mdl
models/mapmodels/barrelcrash.mdl
models/mapmodels/bord.mdl
models/mapmodels/bulb.mdl
models/mapmodels/bush_shrubv01.mdl
models/mapmodels/by_barrel_brown.mdl
models/mapmodels/by_canopy.mdl
models/mapmodels/by_pipe_set1.mdl
models/mapmodels/charlie_wire.mdl
models/mapmodels/cot.mdl
models/mapmodels/cow.mdl
models/mapmodels/desk_office-mahg.mdl
models/mapmodels/elec_box.mdl
models/mapmodels/fan_ceiling-hang.mdl
models/mapmodels/fireplace_logs1.mdl
models/mapmodels/flags.mdl
models/mapmodels/floFDIR_gib.mdl
models/mapmodels/foot_locker.mdl
models/mapmodels/freya_radar1.mdl
models/mapmodels/generator.mdl
models/mapmodels/glider_flight.mdl
models/mapmodels/hedgehog.mdl
models/mapmodels/hk_satchel.mdl
models/mapmodels/jed_begravning.mdl
models/mapmodels/jed_kubelwagen_camo.mdl
models/mapmodels/light_industrial2.mdl
models/mapmodels/null.mdl
models/mapmodels/ouitz_tree1.mdl
models/mapmodels/pi_tree3.mdl
models/mapmodels/railing_turoko.mdl
models/mapmodels/rock_japan_rooftop.mdl
models/mapmodels/rug_oriental-large3.mdl
models/mapmodels/rug_oriental-large5.mdl
models/mapmodels/saint_grass.mdl
models/mapmodels/sign_shop.mdl
models/mapmodels/support_beams1.mdl
models/mapmodels/tnt_crate.mdl
models/mapmodels/waco_glider.mdl
models/mapmodels/wood_barrel1.mdl
models/null.mdl
models/Tnt.mdl
overviews/dod_glider.bmp
overviews/dod_glider.txt
sound/ambience/ambient_spring.wav
sound/ambience/ambient_summer.wav
sound/ambience/birds9.wav
sound/ambience/burning1.wav
sound/ambience/bustmetal2.wav
sound/ambience/cricket.wav
sound/ambience/dodambience4.wav
sound/ambience/drips.wav
sound/ambience/fd.wav
sound/ambience/fd_flyby1.wav
sound/ambience/flyby.wav
sound/ambience/germanwin.wav
sound/ambience/gerobjectivesecure.wav
sound/ambience/glider_radio.wav
sound/ambience/moo.wav
sound/ambience/usobjectivesecure.wav
sound/ambience/uspointcaptured.wav
sound/ambience/uswin.wav
sound/ambience/windy.wav
sound/debris/glass3.wav
sound/player/gerfireinhole.wav
sound/player/usfireinhole.wav
sound/player/usgogogo.wav
sound/weapons/30cal.wav
sound/weapons/30cal_shoot.wav
sprites/flames.spr
sprites/glow01.spr
sprites/icon_obj_axis.spr
sprites/mapsprites/ae_putsatchel2.spr
sprites/mapsprites/ae_satchel2.spr
sprites/mapsprites/c2_5to1count.spr
sprites/mapsprites/caparea.spr
sprites/muzzleflash2.spr
sprites/obj_tnt.spr
sprites/obj_tnt_sm.spr
sprites/smoke_ia.spr
