// \dod_charlie.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (86):
decals.wad
dod_charlie.wad
gfx/env/killertomatobk.tga
gfx/env/killertomatodn.tga
gfx/env/killertomatoft.tga
gfx/env/killertomatolf.tga
gfx/env/killertomatort.tga
gfx/env/killertomatoup.tga
halflife.wad
hlbasics.wad
models/helmet_axis_para.mdl
models/mapmodels/88flak.mdl
models/mapmodels/arc_bush.mdl
models/mapmodels/arc_xer_tree1.mdl
models/mapmodels/barbed_wire.mdl
models/mapmodels/bulb.mdl
models/mapmodels/by_cliff_face.mdl
models/mapmodels/by_pipe_set1.mdl
models/mapmodels/charlie_plans.mdl
models/mapmodels/charlie_shingle.mdl
models/mapmodels/charlie_wire.mdl
models/mapmodels/concretegibs.mdl
models/mapmodels/cow.mdl
models/mapmodels/flags.mdl
models/mapmodels/flo_grass2.mdl
models/mapmodels/forts.mdl
models/mapmodels/hedgehog.mdl
models/mapmodels/hk_busted_mortar.mdl
models/mapmodels/hk_mortar.mdl
models/mapmodels/hk_radio.mdl
models/mapmodels/hk_satchel.mdl
models/mapmodels/ouitz_tree1.mdl
models/mapmodels/panzer.mdl
models/mapmodels/sandbag_gib.mdl
models/mapmodels/sandbags.mdl
models/mapmodels/sherman.mdl
models/mapmodels/smoke_grenade.mdl
models/mapmodels/tnt_crate.mdl
models/mapmodels/zalec_1bulb2wire.mdl
models/mapmodels/zalec_2bulb2wire.mdl
overviews/dod_charlie.bmp
overviews/dod_charlie.txt
sound/ambience/artyboom.wav
sound/ambience/artyhit1.wav
sound/ambience/burning1.wav
sound/ambience/creak.wav
sound/ambience/cricket.wav
sound/ambience/distantmortar2.wav
sound/ambience/dod_jagd_radio.wav
sound/ambience/dodambience6.wav
sound/ambience/drips.wav
sound/ambience/forestmortar.wav
sound/ambience/germanwin.wav
sound/ambience/rocket_groan2.wav
sound/ambience/rocket_groan3.wav
sound/ambience/rocket_steam1.wav
sound/ambience/steamjet1.wav
sound/ambience/tnt_setup.wav
sound/ambience/usobjectivesecure.wav
sound/ambience/uswin.wav
sound/ambience/windy.wav
sound/object/object_dropped.wav
sound/object/object_taken.wav
sound/player/usfireinhole.wav
sound/player/ushold.wav
sound/scientist/donuteater.wav
sound/weapons/garand_shoot.wav
sound/weapons/k43_shoot.wav
sound/weapons/mg42_shoot.wav
sprites/explosion1.spr
sprites/flames.spr
sprites/gas_puff_01.spr
sprites/glow01.spr
sprites/mapsprites/ae_putsatchel2.spr
sprites/mapsprites/ae_satchel2.spr
sprites/mapsprites/c2_5to1count.spr
sprites/mapsprites/explosion_smoke1.spr
sprites/mapsprites/fexplo.spr
sprites/mapsprites/fog6.spr
sprites/mapsprites/kexplosion1.spr
sprites/mg42.spr
sprites/muzzleflash2.spr
sprites/null.spr
sprites/obj_tnt.spr
sprites/obj_tnt_sm.spr
sprites/smoke_ia.spr
