// \dod_saints.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (72):
decals.wad
dod_saints.wad
gfx/env/dmcwbk.tga
gfx/env/dmcwdn.tga
gfx/env/dmcwft.tga
gfx/env/dmcwlf.tga
gfx/env/dmcwrt.tga
gfx/env/dmcwup.tga
hlbasics.wad
models/mapmodels/arc_fern.mdl
models/mapmodels/arc_flower.mdl
models/mapmodels/barbed_wire.mdl
models/mapmodels/bell.mdl
models/mapmodels/bookcase_green.mdl
models/mapmodels/books1.mdl
models/mapmodels/bord.mdl
models/mapmodels/by_barrel_brown.mdl
models/mapmodels/by_canopy.mdl
models/mapmodels/by_rubble_set.mdl
models/mapmodels/car021.mdl
models/mapmodels/couch_fabric-wreck.mdl
models/mapmodels/dod_jagd_car.mdl
models/mapmodels/electric_wire1.mdl
models/mapmodels/fan_ceiling-hang.mdl
models/mapmodels/fireplace_logs1.mdl
models/mapmodels/flags.mdl
models/mapmodels/flo_bed.mdl
models/mapmodels/flo_churchlight.mdl
models/mapmodels/flo_coattree.mdl
models/mapmodels/flo_light.mdl
models/mapmodels/flo_pak37.mdl
models/mapmodels/furniture.mdl
models/mapmodels/jeep.mdl
models/mapmodels/k_bush1.mdl
models/mapmodels/kettenkraftrad.mdl
models/mapmodels/kingtiger.mdl
models/mapmodels/lamp.mdl
models/mapmodels/mattress_wreck.mdl
models/mapmodels/mill.mdl
models/mapmodels/ouitz_tree1.mdl
models/mapmodels/phone_pole1.mdl
models/mapmodels/pine_tree.mdl
models/mapmodels/repunzel_bott.mdl
models/mapmodels/saint_grass.mdl
models/mapmodels/sandbags.mdl
models/mapmodels/shelves_wood.mdl
models/mapmodels/streetlight_saints.mdl
models/mapmodels/streetlight_saints_lt.mdl
models/mapmodels/well.mdl
models/mapmodels/wood_barrel1.mdl
overviews/dod_saints.bmp
overviews/dod_saints.txt
sound/ambience/bell.wav
sound/ambience/burning1.wav
sound/ambience/dodambience4.wav
sound/ambience/fd_flyby2.wav
sound/ambience/forestcreek.wav
sound/ambience/forestcricket.wav
sound/ambience/forestsparrow.wav
sound/ambience/gerareasecure.wav
sound/ambience/germanwin.wav
sound/ambience/jagdbirds.wav
sound/ambience/merderet-bridgeallie.wav
sound/ambience/merderet-bridgeaxis.wav
sound/ambience/mill.wav
sound/ambience/Opera.wav
sound/ambience/usareasecure.wav
sound/ambience/uswin.wav
sprites/flare1.spr
sprites/mapsprites/caparea.spr
sprites/mapsprites/flames.spr
sprites/smoke_ia.spr
