// dod_a32_b1.res - created with RESGen v2.0.3.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (65):
decals.wad
dod_anzio.wad
dod_avalanche.wad
dod_caen.wad
dod_charlie.wad
dod_chemille.wad
dod_donner.wad
dod_escape.wad
dod_falaise.wad
dod_flash.wad
dod_flugplatz.wad
dod_forest.wad
dod_glider.wad
dod_jagd.wad
dod_kalt.wad
dod_kraftstoff.wad
dod_merderet.wad
dod_narby.wad
dod_northbound.wad
dod_saints.wad
dod_sturm.wad
dod_vicenza.wad
dod_zalec.wad
gfx.wad
gfx/env/rubblebk.tga
gfx/env/rubbledn.tga
gfx/env/rubbleft.tga
gfx/env/rubblelf.tga
gfx/env/rubblert.tga
gfx/env/rubbleup.tga
hlbasics.wad
martee.wad
models/mapmodels/88flak.mdl
models/mapmodels/arc_fern.mdl
models/mapmodels/barbed_wire.mdl
models/mapmodels/bulb.mdl
models/mapmodels/by_rubble_set.mdl
models/mapmodels/desk_office-mahg.mdl
models/mapmodels/dinner_table2.mdl
models/mapmodels/dod_jagd_car.mdl
models/mapmodels/flo_grass2.mdl
models/mapmodels/flo_light.mdl
models/mapmodels/furniture.mdl
models/mapmodels/kingtiger.mdl
models/mapmodels/sandbags.mdl
models/mapmodels/street_lamp1.mdl
models/mapmodels/wood_barrel1.mdl
models/w_aflag.mdl
models/w_gflag.mdl
models/w_wflag.mdl
overviews/dod_a32_b1.bmp
overviews/dod_a32_b1.txt
sound/ambience/dodambience1.wav
sound/ambience/gerareasecure.wav
sound/ambience/germanwin.wav
sound/ambience/gerobjectivesecure.wav
sound/ambience/gerpointcaptured.wav
sound/ambience/usareasecure.wav
sound/ambience/usobjectivesecure.wav
sound/ambience/uspointcaptured.wav
sound/ambience/uswin.wav
sprites/glow01.spr
sprites/mapsprites/caparea.spr
sprites/obj_tnt.spr
