// \dod_volonne.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (66):
dod_donner.wad
dod_escape.wad
dod_jagd.wad
dod_kraftstoff.wad
dod_narby.wad
dod_vicenza.wad
dod_volonne.wad
gfx/env/killertomatobk.tga
gfx/env/killertomatodn.tga
gfx/env/killertomatoft.tga
gfx/env/killertomatolf.tga
gfx/env/killertomatort.tga
gfx/env/killertomatoup.tga
hlbasics.wad
models/mapmodels/ae_smallbush.mdl
models/mapmodels/arc_fern.mdl
models/mapmodels/bulb.mdl
models/mapmodels/flo_grass.mdl
models/mapmodels/flo_radio.mdl
models/mapmodels/hk_satchel.mdl
models/mapmodels/mawibse_lamp_01.mdl
models/mapmodels/ouitz_tree1.mdl
models/mapmodels/pine_tree.mdl
models/mapmodels/sandbags.mdl
models/mapmodels/street_lamp1.mdl
models/mapmodels/wood_barrel1.mdl
models/Tnt.mdl
models/w_aflag.mdl
models/w_gflag.mdl
models/w_wflag.mdl
overviews/dod_volonne.bmp
overviews/dod_volonne.txt
sound/ambience/burning1.wav
sound/ambience/crickets.wav
sound/ambience/drips.wav
sound/ambience/forestambience.wav
sound/ambience/forestcricket.wav
sound/ambience/gerareasecure.wav
sound/ambience/germanwin.wav
sound/ambience/gerpointcaptured.wav
sound/ambience/tnt_setup.wav
sound/ambience/usobjectivesecure.wav
sound/ambience/uspointcaptured.wav
sound/ambience/uswin.wav
sound/ambience/waterfall1.wav
sound/ambience/waterfall3.wav
sound/ambience/waterrun.wav
sound/ambience/windy.wav
sound/mapsounds/chimes.wav
sound/mapsounds/unlock.wav
sound/mapsounds/windy.wav
sound/object/object_dropped.wav
sound/object/object_taken.wav
sprites/flames.spr
sprites/gas_puff_01.spr
sprites/glow01.spr
sprites/mapsprites/ae_placetnt.spr
sprites/mapsprites/ae_putsatchel2.spr
sprites/mapsprites/ae_satchel2.spr
sprites/mapsprites/ae_tnt.spr
sprites/mapsprites/c2_5to1count.spr
sprites/mapsprites/caparea.spr
sprites/mapsprites/fog6.spr
sprites/obj_tnt.spr
sprites/obj_tnt_sm.spr
sprites/smoke_ia.spr
