// \dod_hill_classic.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (63):
classic_kleineh_dod.wad
dod_avalanche.wad
dod_caen.wad
dod_charlie.wad
dod_donner.wad
dod_flash.wad
dod_forest.wad
dod_jagd.wad
gfx/env/grnplsntbk.tga
gfx/env/grnplsntdn.tga
gfx/env/grnplsntft.tga
gfx/env/grnplsntlf.tga
gfx/env/grnplsntrt.tga
gfx/env/grnplsntup.tga
hk_rubble.wad
hlbasics.wad
kami-platinum.wad
liquids.wad
models/mapmodels/arc_bush.mdl
models/mapmodels/arc_fern.mdl
models/mapmodels/arc_xer_tree1.mdl
models/mapmodels/arc_xer_tree2.mdl
models/mapmodels/barbed_wire.mdl
models/mapmodels/bord.mdl
models/mapmodels/bulb.mdl
models/mapmodels/by_barrel_brown.mdl
models/mapmodels/by_furniture_group-wreck.mdl
models/mapmodels/concretegibs.mdl
models/mapmodels/forts.mdl
models/mapmodels/hk_mortar.mdl
models/mapmodels/hk_radio.mdl
models/mapmodels/hk_satchel.mdl
models/mapmodels/ouitz_tree1.mdl
models/mapmodels/zalec_1bulb2wire.mdl
models/mapmodels/zalec_2bulb2wire.mdl
models/w_aflag.mdl
models/w_gflag.mdl
overviews/dod_hill_classic.bmp
overviews/dod_hill_classic.txt
seg3-kami.wad
sound/ambience/artyboom.wav
sound/ambience/dodambience2.wav
sound/ambience/forestcreek.wav
sound/ambience/forestmortar.wav
sound/ambience/germanwin.wav
sound/ambience/gerobjectivesecure.wav
sound/ambience/usobjectivesecure.wav
sound/ambience/uswin.wav
sound/ambience/windy.wav
sound/player/usfireinhole.wav
sound/player/ustakecover.wav
sprites/bazookapuff.spr
sprites/glow01.spr
sprites/mapsprites/ae_putsatchel2.spr
sprites/mapsprites/ae_satchel2.spr
sprites/mapsprites/c2_5to1count.spr
sprites/mapsprites/caparea.spr
sprites/obj_tnt.spr
sprites/steam1.spr
surreal1.wad
xeno.wad
xerent.wad
zillafinal.wad
