// \dod_falaise.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (84):
dod_donner.wad
dod_escape.wad
dod_falaise.wad
dod_flugplatz.wad
dod_glider.wad
dod_jagd.wad
gfx/env/kraftstoffbk.tga
gfx/env/kraftstoffdn.tga
gfx/env/kraftstoffft.tga
gfx/env/kraftstofflf.tga
gfx/env/kraftstoffrt.tga
gfx/env/kraftstoffup.tga
halflife.wad
hlbasics.wad
models/mapmodels/88flak.mdl
models/mapmodels/arc_bush.mdl
models/mapmodels/arc_xer_tree1.mdl
models/mapmodels/barbed_wire.mdl
models/mapmodels/barrelcrash.mdl
models/mapmodels/bed_empty-wood.mdl
models/mapmodels/bord.mdl
models/mapmodels/bulb.mdl
models/mapmodels/bush_shrubv01.mdl
models/mapmodels/by_barrel_brown.mdl
models/mapmodels/by_canopy.mdl
models/mapmodels/desk_office-mahg.mdl
models/mapmodels/dod_jagd_tub.mdl
models/mapmodels/fan_ceiling-hang.mdl
models/mapmodels/flo_becken.mdl
models/mapmodels/flo_light.mdl
models/mapmodels/floFDIR_gib.mdl
models/mapmodels/furniture_group-hotel01.mdl
models/mapmodels/grandfather_clock1.mdl
models/mapmodels/hedgehog.mdl
models/mapmodels/jed_begravning.mdl
models/mapmodels/jed_exploding_pine2.mdl
models/mapmodels/jed_kubelwagen_damaged.mdl
models/mapmodels/jed_pines_stumps2.mdl
models/mapmodels/jeep.mdl
models/mapmodels/mattress_wreck.mdl
models/mapmodels/pi_tree3.mdl
models/mapmodels/rock_japan_rooftop.mdl
models/mapmodels/rug_oriental-large3.mdl
models/mapmodels/rug_oriental-large5.mdl
models/mapmodels/saint_grass.mdl
models/mapmodels/shelves_wood.mdl
models/mapmodels/sherman.mdl
models/mapmodels/tiger.mdl
models/mapmodels/waco_glider.mdl
models/mapmodels/wood_barrel1.mdl
models/w_aflag.mdl
models/w_gflag.mdl
models/w_wflag.mdl
overviews/dod_falaise.bmp
overviews/dod_falaise.txt
sound/ambience/ambient_spring.wav
sound/ambience/ambient_summer.wav
sound/ambience/artyboom.wav
sound/ambience/bombnhit.wav
sound/ambience/clock-tic.wav
sound/ambience/cricket.wav
sound/ambience/fan2.wav
sound/ambience/fd.wav
sound/ambience/fd_flyby1.wav
sound/ambience/fd_flyby2.wav
sound/ambience/fd_tree.wav
sound/ambience/fd_v1_sound.wav
sound/ambience/fdmortar.wav
sound/ambience/frenchcountry.wav
sound/ambience/gerareasecure.wav
sound/ambience/germanwin.wav
sound/ambience/gerobjectivesecure.wav
sound/ambience/gerpointcaptured.wav
sound/ambience/truck-1ka.wav
sound/ambience/usareasecure.wav
sound/ambience/usobjectivesecure.wav
sound/ambience/uspointcaptured.wav
sound/ambience/uswin.wav
sound/player/gerenemyahead.wav
sound/player/usenemyahead.wav
sprites/explosion1.spr
sprites/laserbeam.spr
sprites/mapsprites/caparea.spr
sprites/obj_tnt.spr
