// \dod_flugplatz.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (83):
dod_donner.wad
dod_escape.wad
dod_falaise.wad
dod_flugplatz.wad
dod_glider.wad
gfx/env/dashnight256bk.tga
gfx/env/dashnight256dn.tga
gfx/env/dashnight256ft.tga
gfx/env/dashnight256lf.tga
gfx/env/dashnight256rt.tga
gfx/env/dashnight256up.tga
halflife.wad
hlbasics.wad
models/mapmodels/88flak.mdl
models/mapmodels/arc_xer_tree1.mdl
models/mapmodels/big_water_tower.mdl
models/mapmodels/bulb.mdl
models/mapmodels/by_barrel_brown.mdl
models/mapmodels/by_blueprints.mdl
models/mapmodels/by_furniture_group-wreck.mdl
models/mapmodels/by_pipe_set1.mdl
models/mapmodels/by_pipeline_smokestack.mdl
models/mapmodels/by_rubble_set.mdl
models/mapmodels/enginegibs.mdl
models/mapmodels/fd_boxes.mdl
models/mapmodels/filecabinet.mdl
models/mapmodels/furniture.mdl
models/mapmodels/glider_flight.mdl
models/mapmodels/hedgehog.mdl
models/mapmodels/jump_man.mdl
models/mapmodels/kettenkraftrad.mdl
models/mapmodels/me262.mdl
models/mapmodels/null.mdl
models/mapmodels/pallet.mdl
models/mapmodels/panzer.mdl
models/mapmodels/sherman.mdl
models/mapmodels/smoke_grenade.mdl
models/mapmodels/steel_supports1.mdl
models/null.mdl
models/w_aflag.mdl
models/w_gflag.mdl
models/w_wflag.mdl
overviews/dod_flugplatz.bmp
overviews/dod_flugplatz.txt
sound/ambience/aa3.wav
sound/ambience/aa4.wav
sound/ambience/air.wav
sound/ambience/ambient_summer.wav
sound/ambience/artyboom.wav
sound/ambience/burn_no_autostart.wav
sound/ambience/burning1.wav
sound/ambience/dodambience4.wav
sound/ambience/drips.wav
sound/ambience/fan1.wav
sound/ambience/fan2.wav
sound/ambience/fd.wav
sound/ambience/fd_factory.wav
sound/ambience/flyby.wav
sound/ambience/germanwin.wav
sound/ambience/gerobjectivesecure.wav
sound/ambience/glider_radio.wav
sound/ambience/steamburst1.wav
sound/ambience/steamjet1.wav
sound/ambience/usobjectivesecure.wav
sound/ambience/uswin.wav
sound/ambience/windy.wav
sound/player/gerenemyahead.wav
sound/player/gerfallback.wav
sound/player/gersniper.wav
sound/player/usenemyahead.wav
sound/player/usfallback.wav
sound/player/ussniper.wav
sound/weapons/biggun2.wav
sound/weapons/hit_metal1.wav
sound/weapons/hit_metal2.wav
sprites/explosion1.spr
sprites/flames.spr
sprites/glow04.spr
sprites/mapsprites/caparea.spr
sprites/mapsprites/tracers01.spr
sprites/null.spr
sprites/obj_tnt.spr
sprites/smoke_ia.spr
