runs:
  using: composite
  steps:
    - name: Setup OpenSSH
      uses: ./.github/actions/_shared/setup-openssh
    - name: Generate the 'mapcycle.txt' file
      run: ls dodserver/serverfiles/dod/maps/*.bsp | awk -F'/' '{ print $(NF) }' | sed 's/\.bsp$//' | shuf > dodserver/serverfiles/dod/mapcycle.txt
      shell: bash
    - name: "LinuxGSM: Set random default map and max players"
      run: |
        DEFAULT_MAP=$(shuf -n 1 dodserver/serverfiles/dod/mapcycle.txt)
        export VPS_GAMESERVER_CONFIG_DEFAULT_MAP="$DEFAULT_MAP"
        export VPS_GAMESERVER_CONFIG_MAXPLAYERS="${{ env.VPS_GAMESERVER_CONFIG_MAXPLAYERS }}"
        export VPS_GAMESERVER_CONFIG_PINGBOOST="${{ env.VPS_GAMESERVER_CONFIG_PINGBOOST }}"
        export VPS_GAMESERVER_CONFIG_ZONE="${{ env.VPS_GAMESERVER_CONFIG_ZONE }}"
        export VPS_HOSTNAME="${{ env.VPS_HOSTNAME }}"
        envsubst '$VPS_GAMESERVER_CONFIG_DEFAULT_MAP,$VPS_GAMESERVER_CONFIG_MAXPLAYERS,$VPS_GAMESERVER_CONFIG_PINGBOOST,$VPS_GAMESERVER_CONFIG_ZONE,$VPS_HOSTNAME' < dodserver/lgsm/config-lgsm/dodserver/dodserver.cfg.template > dodserver/lgsm/config-lgsm/dodserver/dodserver.cfg
        rm -f dodserver/lgsm/config-lgsm/dodserver/dodserver.cfg.template
      shell: bash
    - name: "Server configuration: Set hostname, RCON password, and download URL"
      run: |
        export VPS_GAMESERVER_CONFIG_FRIENDLYFIRE="${{ env.VPS_GAMESERVER_CONFIG_FRIENDLYFIRE }}"
        export VPS_GAMESERVER_CONFIG_HOSTNAME="${{ env.VPS_GAMESERVER_CONFIG_HOSTNAME }}"
        export VPS_GAMESERVER_CONFIG_MAXRATE="${{ env.VPS_GAMESERVER_CONFIG_MAXRATE }}"
        export VPS_GAMESERVER_CONFIG_MAXUPDATERATE="${{ env.VPS_GAMESERVER_CONFIG_MAXUPDATERATE }}"
        export VPS_GAMESERVER_CONFIG_MINRATE="${{ env.VPS_GAMESERVER_CONFIG_MINRATE }}"
        export VPS_GAMESERVER_CONFIG_MINUPDATERATE="${{ env.VPS_GAMESERVER_CONFIG_MINUPDATERATE }}"
        export VPS_GAMESERVER_CONFIG_RCON_PASSWORD="${{ env.VPS_GAMESERVER_CONFIG_RCON_PASSWORD }}"
        export VPS_GAMESERVER_CONFIG_SYSTICRATE="${{ env.VPS_GAMESERVER_CONFIG_SYSTICRATE }}"
        export VPS_GAMESERVER_CONFIG_TIMELIMIT="${{ env.VPS_GAMESERVER_CONFIG_TIMELIMIT }}"
        export VPS_HOSTNAME="${{ env.VPS_HOSTNAME }}"
        envsubst '$VPS_GAMESERVER_CONFIG_FRIENDLYFIRE,$VPS_GAMESERVER_CONFIG_HOSTNAME,$VPS_GAMESERVER_CONFIG_MAXRATE,$VPS_GAMESERVER_CONFIG_MAXUPDATERATE,$VPS_GAMESERVER_CONFIG_MINRATE,$VPS_GAMESERVER_CONFIG_MINUPDATERATE,$VPS_GAMESERVER_CONFIG_RCON_PASSWORD,$VPS_GAMESERVER_CONFIG_SYSTICRATE,$VPS_GAMESERVER_CONFIG_TIMELIMIT,$VPS_HOSTNAME' < dodserver/serverfiles/dod/dodserver.cfg.template > dodserver/serverfiles/dod/dodserver.cfg
        rm -f dodserver/serverfiles/dod/dodserver.cfg.template
      shell: bash
    - name: "MOTD: Set meta title and iframe source"
      run: |
        export VPS_GAMESERVER_CONFIG_HOSTNAME="${{ env.VPS_GAMESERVER_CONFIG_HOSTNAME }}"
        export VPS_HOSTNAME="${{ env.VPS_HOSTNAME }}"
        envsubst '$VPS_GAMESERVER_CONFIG_HOSTNAME' < dodserver/serverfiles/dod/motd.html.template > dodserver/serverfiles/dod/motd.html
        envsubst '$VPS_GAMESERVER_CONFIG_HOSTNAME,$VPS_HOSTNAME' < dodserver/serverfiles/dod/motd.txt.template > dodserver/serverfiles/dod/motd.txt
        rm -f dodserver/serverfiles/dod/motd.*.template
      shell: bash
    - name: "AMX Mod X: Set admin and moderator users"
      run: |
        export VPS_GAMESERVER_CONFIG_AMXX_ADMINS="${{ env.VPS_GAMESERVER_CONFIG_AMXX_ADMINS }}"
        envsubst '$VPS_GAMESERVER_CONFIG_AMXX_ADMINS' < dodserver/serverfiles/dod/addons/metamod/plugins/amxmodx/configs/users.ini.template > dodserver/serverfiles/dod/addons/metamod/plugins/amxmodx/configs/users.ini
        rm -f dodserver/serverfiles/dod/addons/metamod/plugins/amxmodx/configs/users.ini.template
      shell: bash
    - name: "ReUnion: Set the value of SteamIdHashSalt"
      run: |
        export VPS_GAMESERVER_CONFIG_METAMOD_REUNION_STEAMIDHASHSALT="${{ env.VPS_GAMESERVER_CONFIG_METAMOD_REUNION_STEAMIDHASHSALT }}"
        envsubst '$VPS_GAMESERVER_CONFIG_METAMOD_REUNION_STEAMIDHASHSALT' < dodserver/serverfiles/dod/reunion.cfg.template > dodserver/serverfiles/dod/reunion.cfg
        rm -f dodserver/serverfiles/dod/reunion.cfg.template
      shell: bash
    - name: Set execute permissions for the gaming server files
      run: find dodserver/serverfiles/dod -type f -exec chmod 755 {} \;
      shell: bash
    - name: Synchronize the gaming server files
      run: rsync -e "ssh -i ~/.ssh/${{ env.VPS_GAMESERVER_OPENSSH_ID }}" -avvzP --delete --exclude='.*' ${{ env.VPS_GAMESERVER_RSYNC_SOURCE_PATH }} ${{ env.VPS_GAMESERVER_USERNAME }}@${{ env.VPS_HOSTNAME }}:${{ env.VPS_GAMESERVER_RSYNC_DEST_PATH }}
      shell: bash
