name: Continuous Scheduling
on:
  schedule:
    - cron: 0 5 * * *
env:
  VPS_GAMESERVER_BINARY: ${{ secrets.VPS_GAMESERVER_BINARY }}
  VPS_GAMESERVER_OPENSSH_ID: ${{ secrets.VPS_GAMESERVER_OPENSSH_ID }}
  VPS_GAMESERVER_OPENSSH_PRIVATE_KEY: ${{ secrets.VPS_GAMESERVER_OPENSSH_PRIVATE_KEY }}
  VPS_GAMESERVER_USERNAME: ${{ secrets.VPS_GAMESERVER_USERNAME }}
  VPS_HOSTNAME: ${{ secrets.VPS_HOSTNAME }}
jobs:
  restart-gaming-server:
    name: Restart the gaming server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Restart the gaming server
        uses: ./.github/actions/_shared/restart-gaming-server
  monitor-gaming-server:
    name: Monitor the gaming server
    runs-on: ubuntu-latest
    needs: [restart-gaming-server]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Monitor the gaming server
        uses: ./.github/actions/_shared/monitor-gaming-server
