name: Continuous Deployment
on:
  push:
    branches: [main]
env:
  VPS_GAMESERVER_BINARY: ${{ secrets.VPS_GAMESERVER_BINARY }}
  VPS_GAMESERVER_CONFIG_AMXX_ADMINS: ${{ secrets.VPS_GAMESERVER_CONFIG_AMXX_ADMINS }}
  VPS_GAMESERVER_CONFIG_FRIENDLYFIRE: ${{ vars.VPS_GAMESERVER_CONFIG_FRIENDLYFIRE }}
  VPS_GAMESERVER_CONFIG_HOSTNAME: ${{ vars.VPS_GAMESERVER_CONFIG_HOSTNAME }}
  VPS_GAMESERVER_CONFIG_MAXPLAYERS: ${{ vars.VPS_GAMESERVER_CONFIG_MAXPLAYERS }}
  VPS_GAMESERVER_CONFIG_MAXRATE: ${{ vars.VPS_GAMESERVER_CONFIG_MAXRATE }}
  VPS_GAMESERVER_CONFIG_MAXUPDATERATE: ${{ vars.VPS_GAMESERVER_CONFIG_MAXUPDATERATE }}
  VPS_GAMESERVER_CONFIG_METAMOD_REUNION_STEAMIDHASHSALT: ${{ secrets.VPS_GAMESERVER_CONFIG_METAMOD_REUNION_STEAMIDHASHSALT }}
  VPS_GAMESERVER_CONFIG_MINRATE: ${{ vars.VPS_GAMESERVER_CONFIG_MINRATE }}
  VPS_GAMESERVER_CONFIG_MINUPDATERATE: ${{ vars.VPS_GAMESERVER_CONFIG_MINUPDATERATE }}
  VPS_GAMESERVER_CONFIG_PINGBOOST: ${{ vars.VPS_GAMESERVER_CONFIG_PINGBOOST }}
  VPS_GAMESERVER_CONFIG_RCON_PASSWORD: ${{ secrets.VPS_GAMESERVER_CONFIG_RCON_PASSWORD }}
  VPS_GAMESERVER_CONFIG_SYSTICRATE: ${{ vars.VPS_GAMESERVER_CONFIG_SYSTICRATE }}
  VPS_GAMESERVER_CONFIG_TIMELIMIT: ${{ vars.VPS_GAMESERVER_CONFIG_TIMELIMIT }}
  VPS_GAMESERVER_CONFIG_ZONE: ${{ vars.VPS_GAMESERVER_CONFIG_ZONE }}
  VPS_GAMESERVER_OPENSSH_ID: ${{ secrets.VPS_GAMESERVER_OPENSSH_ID }}
  VPS_GAMESERVER_OPENSSH_PRIVATE_KEY: ${{ secrets.VPS_GAMESERVER_OPENSSH_PRIVATE_KEY }}
  VPS_GAMESERVER_RSYNC_DEST_PATH: ${{ secrets.VPS_GAMESERVER_RSYNC_DEST_PATH }}
  VPS_GAMESERVER_RSYNC_SOURCE_PATH: ${{ secrets.VPS_GAMESERVER_RSYNC_SOURCE_PATH }}
  VPS_GAMESERVER_USERNAME: ${{ secrets.VPS_GAMESERVER_USERNAME }}
  VPS_HOSTNAME: ${{ secrets.VPS_HOSTNAME }}
jobs:
  deploy-gaming-server-files:
    name: Deploy the gaming server files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy the gaming server files
        uses: ./.github/actions/continuous-deployment/deploy-gaming-server-files
  restart-gaming-server:
    name: Restart the gaming server
    runs-on: ubuntu-latest
    needs: [deploy-gaming-server-files]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Restart the gaming server
        uses: ./.github/actions/_shared/restart-gaming-server
